application: efreicalendar
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: efreicalendar.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(\..*)$
- ^(.*/)?.*\.git$